### ISSUE TITLE
getDocumentByIds doees not work: "self" in callables is deprecated

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-php#170]
Method `getDocumentByIds` does not work in PHP 8.2 while `getDocumentById` works fine

```
Unhandled exception Exception with message "Use of "self" in callables is deprecated" in file "/src/app/core.php:360"

* #0 /src/app/core.php(230): App::error('Use of "self" i...')
* 
* #1 [internal function]: App::handleError(8192, 'Use of "self" i...', '/src/app/vendor...', 59)
* 
* #2 /src/app/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Index.php(59): array_walk(Array, 'self::checkDocu...')
* 
* #3 /src/app/src/lib/Manticore.php(268): Manticoresearch\Index->getDocumentByIds(Array)
* 
* #4 /src/app/src/component/Search.php(241): App\Lib\Manticore::getUsers(3266472141, 'user_id')
* 
* #5 /src/app/actions/search.php(122): App\Component\Search::getAuthors(Object(App\Model\Repo))
* 
* #6 /src/app/core.php(174): include('/src/app/action...')
* 
* #7 /src/app/core.php(179): App::{closure}()
* 
* #8 /src/app/main.php(7): App::process()
* 
* #9 {main}
```

**Comment by donhardman** [comment]
This should be fixed in https://github.com/manticoresoftware/manticoresearch-php/pull/172

**Comment by sanikolaev** [comment]
We need to update the readme correspondingly.

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-php/commit/9433630bbd7fc2234717f28898c3c10b597106e8
