### ISSUE TITLE
Can't create a table with a field with a property with a value

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-php#215]
I can't create a table with a field with the property `engine='columnar'`.

```
snikolaev@dev2:~$ cat test_client.php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$config = ['host'=>'127.0.0.1','port'=>9308];
$client = new \Manticoresearch\Client($config);
$index = $client->index('t');
$index->drop(true);
$index->create([
    'a'=>['type'=>'int', 'options' => ['engine' => 'columnar']]
]);
```

```
snikolaev@dev2:~$ php test_client.php
PHP Fatal error:  Uncaught Manticoresearch\Exceptions\ResponseException: "P03: syntax error, unexpected COLUMNAR, expecting ',' or ')' near 'columnar)'" in /home/snikolaev/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Transport/Http.php:127
Stack trace:
#0 /home/snikolaev/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Client.php(372): Manticoresearch\Transport\Http->execute()
#1 /home/snikolaev/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Indices.php(74): Manticoresearch\Client->request()
#2 /home/snikolaev/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Index.php(246): Manticoresearch\Indices->create()
#3 /home/snikolaev/test_client.php(9): Manticoresearch\Index->create()
#4 {main}
  thrown in /home/snikolaev/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Transport/Http.php on line 127
```

The query it generates is:
```
/* Wed Aug 07 11:42:06.862 2024 conn 2213 (127.0.0.1:52026) real 0.000 */ CREATE TABLE t(`a` int columnar);
```

Expected:

```
/* Wed Aug 07 11:42:06.862 2024 conn 2213 (127.0.0.1:52026) real 0.000 */ CREATE TABLE t(`a` int engine='columnar');
```

**Comment by sanikolaev** [comment]
This blocks https://github.com/manticoresoftware/manticoresearch/issues/2348

**Comment by Nick-S-2018** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch-php/commit/096676a93053f2dd7eeb3ce496dc77d7b9e3168b
